import os
import oracledb
from dotenv import load_dotenv

# Carrega o arquivo .env da pasta config
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', 'config', '.env'))

# Carrega variáveis de ambiente com valores padrão para desenvolvimento
USER = os.environ.get("DB_USER", "SYSTEM")
PASSWORD = os.environ.get("DB_PASSWORD", "senha")
DSN = os.environ.get("DB_DSN", "localhost/XE")


def conectar_oracle():
    """Cria e retorna uma conexão Oracle usando variáveis de ambiente.

    Returns:
        oracledb.Connection | None: Objeto de conexão ou None em caso de erro.
    """
    try:
        conn = oracledb.connect(user=USER, password=PASSWORD, dsn=DSN)
        return conn
    except Exception as e:
        print("Erro ao conectar ao Oracle:", e)
        return None


def criar_tabela():
    """Verifica/Cria a tabela `colheitas` se necessário.

    A função trata o caso em que a tabela já existe e confirma a transação.
    """
    conn = conectar_oracle()
    if not conn:
        return

    cursor = conn.cursor()
    try:
        cursor.execute(
            """
            CREATE TABLE colheitas (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tipo VARCHAR2(20),
                prod_estimada FLOAT,
                prod_real FLOAT,
                valor_tonelada FLOAT,
                perda_percentual FLOAT,
                prejuizo FLOAT,
                data VARCHAR2(50)
            )
            """
        )
        conn.commit()
        print("Tabela 'colheitas' verificada/criada com sucesso.")
    except Exception as e:
        # Se já existir, ORA-00955 costuma indicar isso; ignoramos esse caso
        msg = str(e)
        if "ORA-00955" in msg:
            # tabela já existe — não é erro para nosso fluxo
            conn.rollback()
        else:
            # repropaga para que o desenvolvedor veja o problema
            conn.rollback()
            raise
    finally:
        cursor.close()
        conn.close()


def inserir_dados(dados):
    """Insere um registro na tabela `colheitas` usando transação segura.

    Args:
        dados (dict): Dicionário com chaves: tipo, prod_estimada, prod_real,
                      valor_tonelada, perda_percentual, prejuizo, data
    """
    conn = conectar_oracle()
    if not conn:
        print("Não foi possível conectar ao banco para inserir dados.")
        return False

    cursor = conn.cursor()
    try:
        cursor.execute(
            """
            INSERT INTO colheitas (tipo, prod_estimada, prod_real, valor_tonelada, perda_percentual, prejuizo, data)
            VALUES (:tipo, :prod_estimada, :prod_real, :valor_tonelada, :perda_percentual, :prejuizo, :data)
            """,
            dados,
        )
        conn.commit()
        return True
    except Exception as e:
        print(f"Erro ao inserir dados: {e}")
        try:
            conn.rollback()
        except Exception:
            pass
        return False
    finally:
        cursor.close()
        conn.close()


def listar_dados():
    """Retorna todos os registros da tabela `colheitas` como lista de tuplas.

    Returns:
        list[tuple] | None: Lista de registros ou None em caso de erro/conexão.
    """
    conn = conectar_oracle()
    if not conn:
        return None

    cursor = conn.cursor()
    try:
        cursor.execute("SELECT * FROM colheitas")
        registros = cursor.fetchall()
        return registros
    except Exception as e:
        print(f"Erro ao listar dados: {e}")
        return None
    finally:
        cursor.close()
        conn.close()
